# Generated by Django 3.2.5 on 2021-07-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210702_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion_and_beauty',
            name='category',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sports_and_hobbies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='category',
        ),
        migrations.DeleteModel(
            name='Bikes',
        ),
        migrations.DeleteModel(
            name='Fashion_and_beauty',
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
        migrations.DeleteModel(
            name='Mobiles',
        ),
        migrations.DeleteModel(
            name='Sports_and_hobbies',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
